### PR TITLE
Updated links to conform to the HAL format by removing array structure in json.

### PR DESCRIPTION
**Pull request by lukestokes**
Removing the array structure for vnd.error+json to better match the current format of HAL

### CODE REVIEW

**Comment by timbunce** [comment]
The [HAL spec](http://tools.ietf.org/html/draft-kelly-json-hal-05#section-4.1.1) says "values are either a Link Object **or an array** of Link Objects", so there's no need for this change.

**Comment by lukestokes** [comment]
I guess you're technically correct, but implementations of HAL I've seen in the wild usually do not use an array when one is not needed. Meaning, if there is only one link, there's a link object not an array of objects with only one link in it. That's just what I've seen in the wild and if that's what > 50% are use to seeing and working with, than having to retool their clients to deal with an array (which, granted, according to the spec they already should), it makes more sense to me to show examples of a link object when only one link is present.

When I discussed this with Ben via Twitter, he suggested making the change. If it's not needed, he can reject this request or ask me to close it. I have a forked version of the PHP implementation of this which I will continue using if needed for my API. I'd rather not have arrays of links and the spec allows me to make that decision.

**Comment by timbunce** [comment]
Ah, yes. The focus of my comment was on in the "conform to the HAL format" in the title. So I should clarify that I'd be happy to see examples changed to remove the redundant array since that would still conform to the HAL format.

However, as I've said in #8, I'd like to see vnd.error move closer to HAL conformance and so arrays of link objects should still be _allowed_.

**Comment by blongden** [comment]
I think it makes a lot of sense to do this - but specify that arrays are allowed. In the majority, as @lukestokes points out, links are a 1 to 1 to rels. We can still allow multiples as per the HAL spec.

**Pull request merged**
